---
title: "Publications"
---

<br>

1. Callander D., Singham Goodwin A., Duncan D. T., Grov C., El-Sadr W., Grant M., Thompson R. J., Simmons M., Oshiro-Brantly J. L., Bhatt K. J., Meunier É. (2022). **"What will we do if we get infected?": An interview-based study of the COVID-19 pandemic and its effects on the health and safety of sex workers in the United States.** *SSM. Qualitative research in health*, 2, 100027. [https://doi.org/10.1016/j.ssmqr.2021.100027](https://doi.org/10.1016/j.ssmqr.2021.100027)

2. Duncan, D. T., Singham Goodwin, A., Ompad, D. C., & Goodman, M. S. (2021). **Race, Ethnicity, and COVID-19: The Persistence of Black–White Disparities in the United States.** In COVID-19 and Similar Futures: Pandemic Geographies. *Springer International Publishing.* [https://doi.org/10.1007/978-3-030-70179-6](https://doi.org/10.1007/978-3-030-70179-6)

3. Kim, B., Rundle, A., Singham Goodwin, A., Morrison, C. N., Branas, C. C., El-Sadr, W., & Duncan, D. T. (2021). **COVID-19 Testing, Case, and Death Rates and Spatial Socio-Demographics in New York City: An Ecological Analysis as of June 2020.** *Health & Place*. 68, 102539. [https://doi.org/10.1016/j.healthplace.2021.102539] (https://doi.org/10.1016/j.healthplace.2021.102539)

4. Fiori, K., Lauria, M. E., Singer, A. W., Jones, H. E., Belli, H. M., Aylward, P. T., Agoro, S., Gbeleou, S., Sowu, E., Grunitzky-Bekele, M., Singham Goodwin, A., Morrison, M., Ekouevi, D., & Hirschhorn, L. (2021). **Assessment of an integrated primary care initiative to address child health in northern Togo.** *Pediatrics*. [https://pediatrics.aappublications.org/content/early/2021/08/25/peds.2020-035493](https://pediatrics.aappublications.org/content/early/2021/08/25/peds.2020-035493)

5. Callander, D., Meunier, É., DeVeau, R., Grov, C., Donovan, B., Minichiello, V., Goodwin, A. S., & Duncan, D. T. (2020). **Sex workers are returning to work and require enhanced support in the face of COVID-19: Results from a longitudinal analysis of online sex work activity and a content analysis of safer sex work guidelines.** *Sexual Health*, 17(4), 384–386. [https://doi.org/10.1071/SH20128](https://doi.org/10.1071/SH20128)

6. McCarthy, K. J., Braganza, S., Fiori, K., Gbeleou, C., Kpakpo, V., Lopez, A., Schechter, J., Singham Goodwin, A., & Jones, H. E. (2017). **Identifying inequities in maternal and child health through risk stratification to inform health systems strengthening in Northern Togo.** *PloS One,* 12(3), e0173445. [https://doi.org/10.1371/journal.pone.0173445](https://doi.org/10.1371/journal.pone.0173445)

7. Arnold, J., Samson, M., Schechter, J., Goodwin, A. S., Braganza, S., Sesso, G. C., Lopez, A., & Fiori, K. (2016). **Getting There: Overcoming Barriers to Reproductive and Maternal Health Services Access in Northern Togo—A Qualitative Study.** *World Medical & Health Policy*, 8(3), 223–244. [https://doi.org/10.1002/wmh3.195](https://doi.org/10.1002/wmh3.195)